---
- name: "uppp"
  become: true
  apt:
    upgrade: "yes"

- name: "install"
  become: true
  apt: 
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
- name: "ins pm2"
  become: true
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present