version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
            - cd frontend
            - npm install
            - npm run build
          command: |
            echo 'success'
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
          path: ~/spring-tutorial
      - run: cd backend
      - run: npm install
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build            
          command: |  
            - exit 1
      - persist_to_workspace:
          root: ~/
          paths:
            - backend
        
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
