version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd frontend && npm install && npm build
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            echo 'success f'
          when: on_fail
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
  
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: cd backend && npm install && npm run build && npm run start
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build            
          command: |  
            exit 1
          when: on_fail

      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  build-backend2:
    docker:
      - image: cimg/node:14.1.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
            npm run start
            
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:14.1.0
    steps:
      - checkout
      - run: cd frontend && npm install && npm run test
      - restore_cache:
          keys: [frontend-build]
                
  test-backend:
    docker:
      - image: circleci/node:14.1.0
    steps:
      - checkout
      - run: cd backend && npm install  && npm run test
      - restore_cache:
          keys: [backend-build]

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend2
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]